name: ibm-pytorch-projects
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  # Python version
  - python=3.13.9
  
  # Core Data Science Libraries
  - numpy
  - pandas
  - scikit-learn
  - matplotlib
  
  # PyTorch Deep Learning Framework
  - pytorch
  - torchvision 
  
  # For running notebooks
  - jupyterlab
